### ISSUE TITLE
Escaping phred33 score issue

### ISSUE THREAD

**Issue by BioMonster** [ARUP-NGS/StrainTypeMer#7]
A quality score equal to 1 is mapped to a phred33 score of 34. The ascii encoding of 34 is the double quotation mark. On line 161 of straintypemer.sub_commands.compare.py escaping is always done with double quotation marks but the double quotation mark would need to be escaped with single quotation marks. This could potentially be an issue in other places as well.

**Comment by kes1smmn** [comment]
Thanks @BioMonster for noticing this oversight.  I pushed a fix.
